server:
  port: 6688
spring:
  application:
    name: CarbonFootprintTrack
  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

